# Databricks notebook source
import numpy as np

# COMMAND ----------

from_mapping = {
    "Toronto": "Canada", 
    "czech republic": "Czech Republic",
    "Siberia": "Russia",
    "New Hope, PA": "Northeast - USA",
    "boston, ma": "Northeast - USA",
    "Las Vegas, Nevada": "West - USA",
    "Budapest": "Hungary",
    "Russia": "Russia",
    "UNCC": "Northeast - USA",
    "Iceland": "Iceland",
    "International Student": "Unknown",
    "Nepal": "Nepal",
    "Northern New Jersey": "Northeast - USA",
    "NYC-6 yrs. Grew up in Nebraska": "Northeast - USA",
    "philippines": "Philippines",
    "Cambridge, Massachusetts": "Northeast - USA",
    "New Delhi, India": "India",
    "way too little space here. world citizen.": "Unknown",
    "Ottawa, Canada": "Canada",
    "France  / New York": "France",
    "Tokyo and Texas": "Japan",
    "Erie, PA": "Northeast - USA",
    "Westchester, new York": "Northeast - USA",
    "USA/American": "Northeast - USA",
    "Great Neck, NY": "Northeast - USA",
    "California (West Coast)": "West - USA",
    "japan": "Japan",
    "Portland, OR": "West - USA",
    "New York/South Korea/Japan": "South Korea",
    "Dallas, Texas": "South - USA",
    "Bombay, India": "India",
    "Palo Alto, CA": "West - USA",
    "New Mexico": "West - USA",
    "WASHINGTON, D.C.": "Northeast - USA",
    "CALIFORNIA": "West - USA",
    "Manhattan": "Northeast - USA",
    "atlanta, ga": "South - USA",
    "California and New York": "West - USA",
    "Bronx Science": "Northeast - USA",
    "nashville, TN": "South - USA",
    "Australia": "Australia",
    "Toronto, Canada": "Canada",
    "UK/Turkey": "UK",
    "Midwest USA": "Midwest - USA",
    "Costa Rica": "Costa Rica",
    "SOUTH KOREA": "South Korea",
    "Yugoslavia": "Yugoslavia",
    "los angeles": "West - USA",
    "NYC, San Francisco": "Northeast - USA",
    "Oregon": "West - USA",
    "San Francisco, CA": "West - USA",
    "Florida and Virginia": "South - USA",
    "San Francisco Bay Area": "West - USA",
    "Hawaii and Los Angeles": "West - USA",
    "Korea": "South Korea",
    "Paris": "France",
    "france": "France",
    "Austin, TX": "South - USA",
    "Woburn, MA": "Northeast - USA",
    "Greece/Germany": "Greece",
    "TN": "South - USA",
    "Pittsburgh, PA": "Northeast - USA",
    "Hastings-on-Hudson, NY": "Northeast - USA",
    "Milano, Italy": "Italy",
    "poland": "Poland",
    "Burlington, Vermont": "Northeast - USA",
    "Bogota, Colombia": "Colombia",
    "Singapore": "Singapore",
    "Asia, Singapore": "Singapore",
    "Santa Barbara, California": "West - USA",
    "india": "India",
    "Cambridge, MA": "Northeast - USA",
    "Texas/London": "UK",
    "CT, FL, TN": "Northeast - USA",
    "Detroit suburbs": "Midwest - USA",
    "Tokyo, Japan": "Japan",
    "south carolina": "South - USA",
    "California, New Jersey": "West - USA",
    "Belgium": "Belgium",
    "alabama": "South - USA",
    "Westchester County, N.Y.": "Northeast - USA",
    "Romania": "Romania",
    "South Orange, New Jersey": "Northeast - USA",
    "Colombia, South America": "Colombia",
    "Boston, Ma": "Northeast - USA",
    "Kansas City, Missouri": "Midwest - USA",
    "Upstate New York": "Northeast - USA",
    "Manila, Philippines": "Philippines",
    "working": "Unknown",
    "San Diego": "West - USA",
    "Hawaii": "West - USA",
    "Salt Lake City": "West - USA",
    "Saratoga, NY": "Northeast - USA",
    "HKG": "China",
    "BEIJING, CHINA": "China",
    "San Francisco/LA": "West - USA",
    "Born in Iran": "Iran",
    "Persia": "Iran",
    "Indonesia": "Indonesia",
    "India and NJ": "India",
    "Genova, Italy": "Italy",
    "Milan, Italy": "Italy",
    "UK": "UK",
    "London & New York": "UK",
    "New York": "Northeast - USA",
    "New Jersey": "Northeast - USA",
    "California": "West - USA",
    "China": "China",
    "Italy": "Italy",
    "New York City": "Northeast - USA",
    "Boston": "Northeast - USA",
    "Texas": "South - USA",
    "NYC": "Northeast - USA",
    "India": "India",
    "Maryland": "South - USA",
    "Israel": "Israel",
    "Taiwan": "Taiwan",
    "Chicago": "Midwest - USA",
    "Spain": "Spain",
    "Washington, DC": "Northeast - USA",
    "France": "France",
    "San Francisco": "West - USA",
    "Philadelphia": "Northeast - USA",
    "Germany": "Germany",
    "Mexico": "Mexico",
    "NJ": "Northeast - USA",
    "Los Angeles": "West - USA",
    "Connecticut": "Northeast - USA",
    "Pennsylvania": "Northeast - USA",
    "Brooklyn, NY": "Northeast - USA",
    "Miami": "South - USA",
    "Long Island": "Northeast - USA",
    "Minnesota": "Midwest - USA",
    "Hong Kong": "China",
    "Boston, MA": "Northeast - USA",
    "Florida": "South - USA",
    "new york": "Northeast - USA",
    "Canada": "Canada",
    "Greece": "Greece",
    "Michigan": "Midwest - USA",
    "England": "UK",
    "Ohio": "Midwest - USA",
    "Buffalo, NY": "Northeast - USA",
    "Washington DC": "Northeast - USA",
    "Baltimore": "South - USA",
    "Los Angeles, CA": "West - USA",
    "Bangladesh": "Bangladesh",
    "Houston": "South - USA",
    "Brooklyn": "Northeast - USA",
    "PA": "Northeast - USA",
    "New York, NY": "Northeast - USA",
    "Southern California": "West - USA",
    "Northern California": "West - USA",
    "Minneapolis": "Midwest - USA",
    "Atlanta, GA": "South - USA",
    "Ann Arbor, MI": "Midwest - USA",
    "Cincinnati, Ohio": "Midwest - USA",
    "Philippines": "Philippines",
    "Arizona": "West - USA",
    "Kansas": "Midwest - USA",
    "new york city": "Northeast - USA",
    "colorado": "West - USA",
    "Chile": "Chile",
    "North Carolina": "South - USA",
    "Atlanta": "South - USA",
    "Seattle": "West - USA",
    "Massachusetts": "Northeast - USA",
    "Wisconsin": "Midwest - USA",
    "Argentina": "Argentina",
    "London, England": "UK",
    "Colorado": "West - USA",
    "california": "West - USA",
    "Colombia": "Colombia",
    "Indiana": "Midwest - USA",
    "Virginia": "South - USA",
    "I am from NYC": "Northeast - USA",
    "Malaysia, then Massachusetts": "Malaysia",
    "Warsaw, Poland": "Poland",
    "Katonah, NY (more recently, Boston)": "Northeast - USA",
    "Japan": "Japan",
    "Boulder, Colorado": "West - USA",
    "Northern Virginia": "South - USA",
    "Washington, D.C.": "Northeast - USA",
    "Cameroon": "Cameroon",
    "New York Area/ New Jersey": "Northeast - USA",
    "J.P. Morgan": "Unknown",
    "Detroit, Michigan, USA": "Midwest - USA",
    "Pittsburgh": "Northeast - USA",
    "Bulgaria": "Bulgaria",
    "Sweden": "Sweden",
    "Wash DC (4 yrs)": "Northeast - USA",
    "DC": "Northeast - USA",
    "Russia/Germany": "Russia",
    "Rochester, NY": "Northeast - USA",
    "Texas & Boston": "South - USA",
    "Vestal": "Unknown",
    "Long Island, NY": "Northeast - USA",
    "Silver Spring, MD": "South - USA",
    "Taipei, Taiwan": "Taiwan",
    "Berkeley": "West - USA",
    "San Francisco(home)/Los Angeles(undergrad)": "West - USA",
    "SF Bay Area, CA": "West - USA",
    "Shanghai, China": "China",
    "Switzerland": "Switzerland",
    "Panama": "Panama",
    "India/Venezuela": "India",
    "Washington State": "West - USA",
    "spain": "Spain",
    "Minneapolis, MN": "Midwest - USA",
    "NY": "Northeast - USA",
    "P. R. China": "China",
    "Ann Arbor": "Midwest - USA",
    "Cincinnati, OH": "Midwest - USA",
    "Brandeis University": "Northeast - USA",
    "Cherry Hill, NJ": "Northeast - USA",
    "ottawa, canada": "Canada",
    "Philadelphia, PA": "Northeast - USA",
    "Cleveland": "Midwest - USA",
    "NYC (Staten Island)": "Northeast - USA",
    "State College, PA": "Northeast - USA",
    "Detroit": "Midwest - USA",
    "Washington DC Metro Region": "Northeast - USA",
    "Berkeley, CA": "West - USA",
    "Albania": "Albania",
    "Brazil": "Brazil",
    "SIngapore": "Singapore",
    "new jersey": "Northeast - USA",
    "Westchester, NY": "Northeast - USA",
    "Iowa": "Midwest - USA",
    "Bowdoin College": "Northeast - USA",
    "taiwan": "Taiwan",
    "San Diego, CA": "West - USA",
    "Uzbekistan": "Uzbekistan",
    "Nebraska": "Midwest - USA",
    "Queens": "Northeast - USA",
    "nyc": "Northeast - USA",
    "Uruguay": "Uruguay",
    "Alabama": "South - USA",
    "Louisiana": "South - USA",
    "London, UK": "UK",
    "St. Louis, MO": "Midwest - USA",
    "MD": "South - USA",
    "Palm Springs, California": "West - USA",
    "94115": "West - USA",
    "Milan - Italy": "Italy",
    "Georgia, USA": "South - USA",
    "Tuscaloosa, Alabama": "South - USA",
    "Albuquerque, NM": "West - USA",
    "Palo Alto, California": "West - USA",
    "Torrance, CA": "West - USA",
    "Azerbaijan": "Azerbaijan",
    "India, Holland": "India",
    "Milwaukee, Wisconsin": "Midwest - USA",
    "brooklyn ny": "Northeast - USA",
    "Puerto Rico": "Puerto Rico",
    "Memphis, TN": "South - USA",
    "Staten Island": "Northeast - USA",
    "Born in Montana, raised in South Jersey (nr. Philadelphia)": "West - USA",
    "uruguay": "Uruguay",
    "Portland, Oregon": "West - USA",
    "Lexington, MA": "Northeast - USA",
    "brooklyn, ny": "Northeast - USA",
    "Toronto, London, India": "India",
    "lOS aNGELES": "West - USA",
    "Europe": "Unknown",
    "Greenwich, CT": "Northeast - USA",
    "sofia, bg": "Bulgaria",
    "china": "China",
    "Pougkeepsie NY": "Northeast - USA"
}

# COMMAND ----------

continent_mapping = {
    "Northeast - USA": "North America",
    "West - USA": "North America",
    "South - USA": "North America",
    "Midwest - USA": "North America",
    "China": "Asia",
    "India": "Asia",
    "Italy": "Europe",
    "UK": "Europe",
    "France": "Europe",
    "Taiwan": "Asia",
    "Canada": "North America",
    "Spain": "Europe",
    "Russia": "Europe",
    "Israel": "Asia",
    "Unknown": "Unknown",
    "Germany": "Europe",
    "Mexico": "North America",
    "Greece": "Europe",
    "Japan": "Asia",
    "Philippines": "Asia",
    "Singapore": "Asia",
    "Colombia": "South America",
    "South Korea": "Asia",
    "Iran": "Asia",
    "Bangladesh": "Asia",
    "Poland": "Europe",
    "Chile": "South America",
    "Argentina": "South America",
    "Bulgaria": "Europe",
    "Indonesia": "Asia",
    "Iceland": "Europe",
    "Czech Republic": "Europe",
    "Nepal": "Asia",
    "Malaysia": "Asia",
    "Hungary": "Europe",
    "Yugoslavia": "Europe",  
    "Costa Rica": "South America", 
    "Australia": "Australia/Oceania",
    "Cameroon": "Africa",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Uruguay": "South America",
    "Panama": "South America", 
    "Brazil": "South America",
    "Albania": "Europe",
    "Belgium": "Europe",
    "Romania": "Europe",
    "Azerbaijan": "Asia",  
    "Puerto Rico": "North America",
    "Uzbekistan": "Asia"
}

# COMMAND ----------

uni_mapping = {
    "UC Berkeley": "University of California, Berkeley",
    "Harvard": "Harvard University",
    "Columbia": "Columbia University",
    "Yale": "Yale University",
    "NYU": "New York University",
    "UCLA": "University of California, Los Angeles",
    "Brown": "Brown University",
    "Cornell University": "Cornell University",
    "Smith College": "Smith College",
    "Tufts University": "Tufts University",
    "Cornell": "Cornell University",
    "Columbia College": "Columbia University",
    "Rutgers College": "Rutgers University",
    "Columbia University": "Columbia University",
    "University of Toronto": "University of Toronto",
    "Barnard College": "Barnard College",
    "University of Pennsylvania": "University of Pennsylvania",
    "Wesleyan University": "Wesleyan University",
    "Harvard University": "Harvard University",
    "University of Michigan": "University of Michigan",
    "University of Vermont": "University of Vermont",
    "Penn State University": "Pennsylvania State University",
    "Connecticut College": "Connecticut College",
    "Tufts": "Tufts University",
    "Florida International University": "Florida International University",
    "University of Washington": "University of Washington",
    "Brown University": "Brown University",
    "Delhi University": "University of Delhi",
    "Princeton": "Princeton University",
    "UC Irvine": "University of California, Irvine",
    "Georgetown University": "Georgetown University",
    "University of California at Santa Barbara": "University of California, Santa Barbara",
    "Holy Cross": "College of the Holy Cross",
    "Boston College": "Boston College",
    "Stanford University": "Stanford University",
    "Fordham University": "Fordham University",
    "Amherst College": "Amherst College",
    "Rutgers University": "Rutgers University",
    "Bucknell University": "Bucknell University",
    "Hamilton College": "Hamilton College",
    "Oxford": "University of Oxford",
    "LUISS, Rome": "LUISS Guido Carli University",
    "Universidad de Chile": "Universidad de Chile",
    "S.V Regional Engineering College,India": "unknown",
    "University of Southern California": "University of Southern California",
    "Princeton University": "Princeton University",
    "University of Kansas": "University of Kansas",
    "Nirma Institute of Technology-India": "Nirma University",
    "SEAS": "unknown",
    "Dartmouth College": "Dartmouth College",
    "Cooper Union, Bard college, and SUNY Purchase": "unknown",
    "Naples, Italy": "University of Naples Federico II",
    "U.C. Berkeley": "University of California, Berkeley",
    "Loyola College": "Loyola University Maryland",
    "Texas State University": "Texas State University",
    "University of Genova": "University of Genoa",
    "University of Reading, England": "University of Reading",
    "Oxford University": "University of Oxford",
    "Univeristy of California, Davis": "University of California, Davis",
    "COOPER UNION": "Cooper Union",
    "Tianjin University in China": "Tianjin University",
    "University of Cologne, Germany": "University of Cologne",
    "ColumbiaU": "Columbia University",
    "Conneticut College": "Connecticut College",
    "Beijing University": "Peking University",
    "Georgetown": "Georgetown University",
    "Santa Clara University": "Santa Clara University",
    "Southwestern University": "Southwestern University",
    "California State University Los Angeles": "California State University, Los Angeles",
    "Ecole Normale Sup\x8erieure, Paris": "École Normale Supérieure",
    "U of  Michigan": "University of Michigan",
    "charles university, prague, czech republic": "Charles University",
    "tech school": "unknown",
    "Queens College": "Queens College, City University of New York",
    "Emory University": "Emory University",
    "MIT": "Massachusetts Institute of Technology",
    "Harvey Mudd College (Physics)": "Harvey Mudd College",
    "Sarah Lawrence College": "Sarah Lawrence College",
    "Columbia Business School": "Columbia Business School, Columbia University",
    "REC, Rourkela": "National Institute of Technology Rourkela",
    "University of North Carolina at Charlotte": "University of North Carolina at Charlotte",
    "UNLV": "University of Nevada, Las Vegas",
    "umass": "University of Massachusetts Amherst",
    "RPI": "Rensselaer Polytechnic Institute",
    "Novosibirsk State University": "Novosibirsk State University",
    "MSU, Russia": "Lomonosov Moscow State University",
    "PACE University": "Pace University",
    "Syracuse University": "Syracuse University",
    "University of Paris": "University of Paris",
    "Brandeis University": "Brandeis University",
    "Tokyo Woman's Christian University, Japan": "Tokyo Woman's Christian University",
    "University of Maryland, and Oxford": "unknown",
    "UW Madison": "University of Wisconsin-Madison",
    "Universidad Iberoamericana": "Universidad Iberoamericana",
    "Rice": "Rice University",
    "University of Warsaw": "University of Warsaw",
    "Stanford": "Stanford University",
    "colby college, waterville, me": "Colby College",
    "ChungShenMedicalUniversity(Taiwan)": "Chung Shan Medical University",
    "lipscomb university": "Lipscomb University",
    "Northwestern University": "Northwestern University",
    "nyu": "New York University",
    "u of southern california, economics": "University of Southern California",
    "University of Texas": "University of Texas at Austin",
    "Universidad de Costa Rica": "Universidad de Costa Rica",
    "Harvard College": "Harvard College, Harvard University",
    "Illinois": "University of Illinois at Urbana-Champaign",
    "Cambridge University": "University of Cambridge",
    "Monash University - Australia": "Monash University",
    "HEC FRance": "HEC Paris",
    "SOGANG UNIVERSITY(KOREA)": "Sogang University",
    "Univeristy of Barcelona": "University of Barcelona",
    "Occidental College": "Occidental College",
    "Mary Baldwin College": "Mary Baldwin University",
    "Colgate University": "Colgate University",
    "University of Oregon": "University of Oregon",
    "Bowdoin College": "Bowdoin College",
    "School of the Arts": "unknown",
    "Ecole Polytechnique (France)": "École Polytechnique",
    "Hofstra University": "Hofstra University",
    "uni. of jordan": "University of Jordan",
    "Vanderbilt University": "Vanderbilt University",
    "Manhattan College": "Manhattan College",
    "Wesleyan": "Wesleyan University",
    "Al-Azhar University": "Al-Azhar University",
    "Dartmouth": "Dartmouth College",
    "Rutgers": "Rutgers University",
    "Kansas": "University of Kansas",
    "Vanderbilt": "Vanderbilt University",
    "Univeristy of Michigan": "University of Michigan",
    "Amherst": "Amherst College",
    "MIT, Cambridge, MA": "Massachusetts Institute of Technology",
    "School of Oriental and African Studies, University of London": "School of Oriental and African Studies",
    "UW-Madison": "University of Wisconsin-Madison",
    "Delhi School of Economics": "Delhi School of Economics",
    "LSE": "London School of Economics and Political Science",
    "Northwestern": "Northwestern University",
    "columbia": "Columbia University",
    "SUNY Stony Brook": "Stony Brook University",
    "UNAM Mexico": "Universidad Nacional Autónoma de México",
    "University of Minnesota": "University of Minnesota",
    "University of Hyderabad": "University of Hyderabad",
    "University of Michigan, Ann Arbor": "University of Michigan",
    "Williams College": "Williams College",
    "University of Nebraska": "University of Nebraska-Lincoln",
    "University of British Columbia": "University of British Columbia",
    "Notre Dame": "University of Notre Dame",
    "Georgetown U": "Georgetown University",
    "National University of Singapore": "National University of Singapore",
    "Vrije Universiteit Brussel, Belgium": "Vrije Universiteit Brussel",
    "Bowdoin": "Bowdoin College",
    "National University of Colombia": "National University of Colombia",
    "Univeristy of Georgia": "University of Georgia",
    "American University": "American University",
    "Middlebury College": "Middlebury College",
    "Johns Hopkins University": "Johns Hopkins University",
    "Ecole des Mines": "École des Mines",
    "MIT, Sloan": "MIT Sloan School of Management",
    "uni. of tehran": "University of Tehran",
    "Scripps College": "Scripps College",
    "Colby College": "Colby College",
    "Simon Fraser University": "Simon Fraser University",
    "Bocconi": "Bocconi University",
    "Peking University": "Peking University",
    "Hampshire College": "Hampshire College",
    "University of Florida": "University of Florida",
    "Universidad Cat\x9alica, Chile": "Pontificia Universidad Católica de Chile",
    "UC Riverside": "University of California, Riverside",
    "Carleton College": "Carleton College",
    "Kyung Hee University(KOREA)": "Kyung Hee University",
    "Tel Aviv University": "Tel Aviv University",
    "Drexel": "Drexel University",
    "Univeristy of Illinois Urbana Champaign": "University of Illinois at Urbana-Champaign",
    "Middle East Technical University": "Middle East Technical University",
    "UC Davis": "University of California, Davis",
    "University of Western Australia": "University of Western Australia",
    "Hong Kong University": "University of Hong Kong",
    "University of Virginia": "University of Virginia",
    "Northwestern, UCLA, USC": "unknown",
    "Tel Aviv": "Tel Aviv University",
    "University of San Francisco": "University of San Francisco",
    "George Washington University": "George Washington University",
    "IIT Madras": "Indian Institute of Technology Madras",
    "Yale College": "Yale College, Yale University",
    "Texas A&M University": "Texas A&M University",
    "Helsinki, Finland": "University of Helsinki",
    "University of Wisconsin": "University of Wisconsin-Madison",
    "university of california, berkeley": "University of California, Berkeley",
    "Instituto Tecnológico Autónomo de México": "Instituto Tecnológico Autónomo de México",
    "Waseda University Japan": "Waseda University",
    "University of Missouri": "University of Missouri",
    "Swarthmore College": "Swarthmore College",
    "UPENN": "University of Pennsylvania",
    "USC": "University of Southern California",
    "McGill University": "McGill University",
    "Indiana University": "Indiana University Bloomington",
    "University of Texas at Austin": "University of Texas at Austin",
    "Wellesley College": "Wellesley College",
    "UMD": "University of Maryland, College Park",
    "Barnard": "Barnard College",
    "UNISA, South Africa": "University of South Africa",
    "Harvard U": "Harvard University",
    "Hanyang University Korea": "Hanyang University",
    "Virginia": "University of Virginia",
    "University of California at Los Angeles": "University of California, Los Angeles",
    "National Taiwan University": "National Taiwan University",
    "Pune University": "Savitribai Phule Pune University",
    "Bryn Mawr College": "Bryn Mawr College",
    "Carnegie Mellon University": "Carnegie Mellon University",
    "university of chicago": "University of Chicago",
    "Duke University": "Duke University",
    "Beloit College": "Beloit College",
    "University of Rochester": "University of Rochester",
    "Fisk University": "Fisk University",
    "Emory": "Emory University",
    "St. Lawrence University": "St. Lawrence University",
    "Universidad Nacional de Colombia": "Universidad Nacional de Colombia",
    "U of Illinois Urbana-Champaign": "University of Illinois at Urbana-Champaign",
    "Penn": "University of Pennsylvania",
    "Univeristy of Massachusetts Amherst": "University of Massachusetts Amherst",
    "Reed College": "Reed College",
    "University of Auckland": "University of Auckland",
    "IIT Kanpur": "Indian Institute of Technology Kanpur",
    "CUNY": "City University of New York",
    "Bates College": "Bates College",
    "Fudan University": "Fudan University",
    "Skidmore College": "Skidmore College",
    "University of Hawaii": "University of Hawaii at Manoa",
    "Lomonosov Moscow State University": "Lomonosov Moscow State University",
    "Vassar College": "Vassar College",
    "university of massachusetts": "University of Massachusetts Amherst",
    "Fordham": "Fordham University",
    "university of houston": "University of Houston",
    "Loyola University": "Loyola University Chicago",
    "University of Minnesota Twin Cities": "University of Minnesota",
    "Tsinghua University": "Tsinghua University",
    "Victoria University of Wellington": "Victoria University of Wellington",
    "Wake Forest University": "Wake Forest University",
    "University of Delhi": "University of Delhi",
    "Tufts University": "Tufts University",
    "UC Berkeley": "University of California, Berkeley",
    "University of Kansas, Lawrence": "University of Kansas",
    "UCLA": "University of California, Los Angeles",
    "Monash University": "Monash University",
    "King's College London": "King's College London",
    "University of Maryland": "University of Maryland, College Park",
    "Pomona College": "Pomona College",
    "UQAM, Canada": "Université du Québec à Montréal",
    "university of toronto": "University of Toronto",
    "University of York": "University of York",
    "Haverford College": "Haverford College",
    "Brandeis": "Brandeis University",
    "McMaster University": "McMaster University",
    "Occidental College": "Occidental College",
    "Lancaster University": "Lancaster University",
    "Texas": "University of Texas at Austin",
    "UBC": "University of British Columbia",
    "Georgetown": "Georgetown University",
    "University of Tokyo": "University of Tokyo",
    "City University of New York": "City University of New York",
    "University of Texas at Dallas": "University of Texas at Dallas",
    "University of Colorado": "University of Colorado Boulder",
    "Rice University": "Rice University",
    "University of Maryland College Park": "University of Maryland, College Park",
    "Harvard": "Harvard University",
    "UT Dallas": "University of Texas at Dallas",
    "university of washington": "University of Washington",
    "Yale": "Yale University",
    "Nanjing University": "Nanjing University",
    "Smith College": "Smith College",
    "California Institute of Technology": "California Institute of Technology",
    "Iowa State University": "Iowa State University",
    "University of Notre Dame, Indiana": "University of Notre Dame",
    "University of Edinburgh": "University of Edinburgh",
    "Princeton": "Princeton University",
    "Keio University Japan": "Keio University",
    "Kyoto University": "Kyoto University",
    "Brown": "Brown University",
    "Yonsei University, Korea": "Yonsei University",
    "Brandeis University": "Brandeis University",
    "University of Iowa": "University of Iowa",
    "University of Pittsburgh": "University of Pittsburgh",
    "New York University": "New York University",
    "Rensselaer Polytechnic Institute": "Rensselaer Polytechnic Institute",
    "Stanford University": "Stanford University",
    "university of oregon": "University of Oregon",
    "National University of Singapore (NUS)": "National University of Singapore",
    "SUNY Albany": "University at Albany, SUNY",
    "Hebrew University of Jerusalem": "Hebrew University of Jerusalem",
    "University of Wisconsin, Madison": "University of Wisconsin-Madison",
    "Tulane University": "Tulane University",
    "Oxford": "University of Oxford",
    "university of illinois": "University of Illinois at Urbana-Champaign",
    "University of Tokyo, Japan": "University of Tokyo",
    "University of California at Berkeley": "University of California, Berkeley",
    "Baylor University": "Baylor University",
    "university of california, davis": "University of California, Davis",
    "Birkbeck College, University of London": "Birkbeck, University of London",
    "University of Pennsylvania": "University of Pennsylvania",
    "University of North Carolina at Chapel Hill": "University of North Carolina at Chapel Hill",
    "Osmania University": "Osmania University",
    "University of Michigan at Ann Arbor": "University of Michigan",
    "The George Washington University": "George Washington University",
    "university of southern california": "University of Southern California",
    "University of Arizona": "University of Arizona",
    "University of Sussex": "University of Sussex",
    "Southern Methodist University": "Southern Methodist University",
    "U. of California, Los Angeles": "University of California, Los Angeles",
    "University of London": "University of London",
    "University of Melbourne": "University of Melbourne",
    "University of North Carolina": "University of North Carolina at Chapel Hill",
    "University of Connecticut": "University of Connecticut",
    "Syracuse": "Syracuse University",
    "Northeastern University": "Northeastern University",
    "University of Miami": "University of Miami",
    "Brigham Young University": "Brigham Young University",
    "university of arizona": "University of Arizona",
    "Illinois": "University of Illinois at Urbana-Champaign",
    "University of Kentucky": "University of Kentucky",
    "Univeristy of South Florida": "University of South Florida",
    "Lehigh University": "Lehigh University",
    "Syracuse University": "Syracuse University",
    "IIT Bombay": "Indian Institute of Technology Bombay",
    "Stanford": "Stanford University",
    "Boston University": "Boston University",
    "Boston College": "Boston College",
    "University of Texas": "University of Texas at Austin",
    "State University of New York at Stony Brook": "Stony Brook University",
    "UCSD": "University of California, San Diego",
    "University of South Carolina": "University of South Carolina",
    "university of michigan": "University of Michigan",
    "State University of New York at Buffalo": "University at Buffalo, SUNY",
    "U of C": "University of Calgary or University of Chicago (context dependent)",
    "University of Alberta": "University of Alberta",
    "San Francisco State University": "San Francisco State University",
    "UC Santa Barbara": "University of California, Santa Barbara",
    "University of Illinois at Urbana-Champaign": "University of Illinois at Urbana-Champaign",
    "UCI": "University of California, Irvine",
    "University of Utah": "University of Utah",
    "University of Houston": "University of Houston",
    "University of Washington, Seattle": "University of Washington",
    "St. John's University": "St. John's University",
    "University of New Hampshire": "University of New Hampshire",
    "Duke": "Duke University",
    "Western Michigan University": "Western Michigan University",
    "University of Colorado at Boulder": "University of Colorado Boulder",
    "university of california, los angeles": "University of California, Los Angeles",
    "Tulane": "Tulane University",
    "Cambridge": "University of Cambridge",
    "Cornell University": "Cornell University",
    "USP, Brazil": "Universidade de São Paulo",
    "Temple": "Temple University",
    "University of California at Davis": "University of California, Davis",
    "San Diego State University": "San Diego State University",
    "University of New Mexico": "University of New Mexico",
    "Purdue": "Purdue University",
    "The City University of New York": "City University of New York",
    "university of florida": "University of Florida",
    "university of pennsylvania": "University of Pennsylvania",
    "Yale University": "Yale University",
    "University of Rochester": "University of Rochester",
    "UT Austin": "University of Texas at Austin",
    "University of Oklahoma": "University of Oklahoma",
    "Rutgers": "Rutgers, The State University of New Jersey",
    "Northwestern University": "Northwestern University",
    "university of minnesota": "University of Minnesota",
    "Johns Hopkins": "Johns Hopkins University",
    "Dartmouth": "Dartmouth College",
    "University of Nebraska": "University of Nebraska-Lincoln",
    "Columbia": "Columbia University in the City of New York",
    "university of california, san diego": "University of California, San Diego",
    "MIT": "Massachusetts Institute of Technology",
    "University of Virginia": "University of Virginia",
    "Washington University in St. Louis": "Washington University in St. Louis",
    "Louisiana State University": "Louisiana State University",
    "University of California, Riverside": "University of California, Riverside",
    "university of virginia": "University of Virginia",
    "university of california, irvine": "University of California, Irvine",
    "NYU": "New York University",
    "Ohio State University": "Ohio State University",
    "Rutgers University": "Rutgers, The State University of New Jersey",
    "University of British Columbia, Canada": "University of British Columbia",
    "Emory": "Emory University",
    "University of Georgia": "University of Georgia",
    "University of Oregon": "University of Oregon",
    "University of Massachusetts, Amherst": "University of Massachusetts Amherst",
    "Vanderbilt": "Vanderbilt University",
    "Dartmouth College": "Dartmouth College",
    "Loyola University Chicago": "Loyola University Chicago",
    "university of california, berkeley": "University of California, Berkeley",
    "University of Wisconsin": "University of Wisconsin-Madison",
    "Columbia University": "Columbia University in the City of New York",
    "Indiana University": "Indiana University Bloomington",
    "University of Tennessee": "University of Tennessee, Knoxville",
    "university of chicago": "University of Chicago",
    "North Carolina State University": "North Carolina State University",
    "Rice": "Rice University",
    "University of California at San Diego": "University of California, San Diego",
    "University of California at Los Angeles": "University of California, Los Angeles",
    "university of maryland": "University of Maryland, College Park",
    "university of colorado": "University of Colorado Boulder",
    "University of Missouri": "University of Missouri-Columbia",
    "Princeton University": "Princeton University",
    "university of notre dame": "University of Notre Dame",
    "Duke University": "Duke University",
    "Washington State University": "Washington State University",
    "University of California, San Diego": "University of California, San Diego",
    "USC": "University of Southern California",
    "Fordham University": "Fordham University",
    "University of Chicago": "University of Chicago",
    "University of California, Santa Cruz": "University of California, Santa Cruz",
    "University of Cincinnati": "University of Cincinnati",
    "University of Florida": "University of Florida",
    "Case Western Reserve University": "Case Western Reserve University",
    "UC Davis": "University of California, Davis",
    "University of California at Santa Barbara": "University of California, Santa Barbara",
    "Penn": "University of Pennsylvania",
    "Florida State University": "Florida State University",
    "UC Santa Cruz": "University of California, Santa Cruz",
    "University of Southern California": "University of Southern California",
    "University of California, Berkeley": "University of California, Berkeley",
    "University of Virginia at Charlottesville": "University of Virginia",
    "university of texas at austin": "University of Texas at Austin",
    "Texas A&M University": "Texas A&M University",
    "university of california, santa barbara": "University of California, Santa Barbara",
    "Michigan State University": "Michigan State University",
    "University of Iowa, Iowa City": "University of Iowa",
    "university of california, santa cruz": "University of California, Santa Cruz",
    "university of wisconsin": "University of Wisconsin-Madison",
    "University of South Florida": "University of South Florida",
    "University of Texas at Austin": "University of Texas at Austin",
    "University of Hawaii": "University of Hawaii at Manoa",
    "Georgetown University": "Georgetown University",
    "university of hawaii": "University of Hawaii at Manoa",
    "University of North Carolina, Chapel Hill": "University of North Carolina at Chapel Hill",
    "university of illinois at urbana-champaign": "University of Illinois at Urbana-Champaign",
    "university of georgia": "University of Georgia",
    "university of north carolina": "University of North Carolina at Chapel Hill",
    "Vanderbilt University": "Vanderbilt University",
    "university of california, riverside": "University of California, Riverside",
    "Harvard University": "Harvard University",
    "university of iowa": "University of Iowa",
    "Purdue University": "Purdue University",
    "university of california, san francisco": "University of California, San Francisco",
    "Texas Tech University": "Texas Tech University",
    "University of California, Irvine": "University of California, Irvine",
    "university of south florida": "University of South Florida",
    "University of Kansas": "University of Kansas",
    "university of california, santa cruz, ca": "University of California, Santa Cruz",
    "university of massachusetts, amherst": "University of Massachusetts Amherst",
    "University of Mississippi": "University of Mississippi",
    "university of pittsburgh": "University of Pittsburgh",
    "university of rochester": "University of Rochester",
    "Rochester": "University of Rochester",
    "University of North Carolina, Greensboro": "University of North Carolina at Greensboro",
    "university of southern california, los angeles": "University of Southern California",
    "university of texas": "University of Texas at Austin",
    "university of utah": "University of Utah",
    "university of washington, seattle": "University of Washington",
    "University of Delaware": "University of Delaware",
    "university of kansas": "University of Kansas",
    "University of California, Los Angeles (UCLA)": "University of California, Los Angeles",
    "university of north carolina, chapel hill": "University of North Carolina at Chapel Hill",
    "University of Alabama, Tuscaloosa": "University of Alabama",
    "university of california, los angeles": "University of California, Los Angeles",
    "Stanford University": "Stanford University",
    "Brown University": "Brown University",
    "University of Texas, Austin": "University of Texas at Austin",
    "Cornell University": "Cornell University",
    "university of california, davis": "University of California, Davis",
    "University of North Carolina at Charlotte": "University of North Carolina at Charlotte",
    "university of california, davis, ca": "University of California, Davis",
    "university of california, berkeley, ca": "University of California, Berkeley",
    "University of Miami": "University of Miami",
    "Baylor University": "Baylor University",
    "University of Michigan": "University of Michigan",
    "university of colorado, boulder": "University of Colorado Boulder",
    "University of Michigan, Ann Arbor": "University of Michigan-Ann Arbor",
    "university of illinois": "University of Illinois at Urbana-Champaign",
    "university of miami": "University of Miami",
    "university of michigan": "University of Michigan",
    "University of Illinois, Urbana-Champaign": "University of Illinois at Urbana-Champaign",
    "university of california, berkeley, california": "University of California, Berkeley",
    "university of michigan, ann arbor": "University of Michigan-Ann Arbor",
    "university of colorado, denver": "University of Colorado Denver",
    "Tufts University": "Tufts University",
    "university of colorado, colorado springs": "University of Colorado Colorado Springs",
    "university of california, berkeley, ca, usa": "University of California, Berkeley",
    "University of California, Berkeley, USA": "University of California, Berkeley",
    "university of illinois, urbana-champaign": "University of Illinois at Urbana-Champaign",
    "university of california, los angeles, ca, usa": "University of California, Los Angeles",
    "university of colorado, boulder, co": "University of Colorado Boulder",
    "University of Colorado, Boulder, CO": "University of Colorado Boulder",
    "university of florida, gainesville": "University of Florida",
    "University of Florida, Gainesville": "University of Florida",
    "university of illinois, urbana-champaign, il": "University of Illinois at Urbana-Champaign",
    "University of Illinois, Urbana-Champaign, IL": "University of Illinois at Urbana-Champaign",
    "university of maryland, college park": "University of Maryland, College Park",
    "university of massachusetts": "University of Massachusetts Amherst",
    "University of Maryland, College Park, MD": "University of Maryland, College Park",
    "university of minnesota, twin cities": "University of Minnesota Twin Cities",
    "University of Minnesota, Twin Cities": "University of Minnesota Twin Cities",
    "university of nebraska": "University of Nebraska-Lincoln",
    "University of Nebraska, Lincoln": "University of Nebraska-Lincoln",
    "university of nevada, las vegas": "University of Nevada, Las Vegas",
    "University of Nevada, Las Vegas": "University of Nevada, Las Vegas",
    "university of north carolina, charlotte": "University of North Carolina at Charlotte",
    "University of North Carolina, Charlotte": "University of North Carolina at Charlotte",
    "university of north texas": "University of North Texas",
    "University of North Texas": "University of North Texas",
    "university of oregon, eugene": "University of Oregon",
    "University of Oregon, Eugene": "University of Oregon",
    "university of pittsburgh, pittsburgh": "University of Pittsburgh",
    "University of Pittsburgh, Pittsburgh": "University of Pittsburgh",
    "university of south carolina": "University of South Carolina",
    "University of South Carolina": "University of South Carolina",
    "university of tennessee, knoxville": "University of Tennessee, Knoxville",
    "University of Tennessee, Knoxville": "University of Tennessee, Knoxville",
    "university of texas, austin": "University of Texas at Austin",
    "University of Texas, Austin": "University of Texas at Austin",
    "university of utah, salt lake city": "University of Utah",
    "University of Utah, Salt Lake City": "University of Utah",
    "university of washington": "University of Washington",
    "University of Washington": "University of Washington",
    "university of wisconsin, madison": "University of Wisconsin-Madison",
    "University of Wisconsin, Madison": "University of Wisconsin-Madison",
    "university of wyoming": "University of Wyoming",
    "University of Wyoming": "University of Wyoming",
    "vanderbilt university": "Vanderbilt University",
    "Vanderbilt University": "Vanderbilt University",
    "virginia tech": "Virginia Tech",
    "Virginia Tech": "Virginia Tech",
    "wake forest university": "Wake Forest University",
    "Wake Forest University": "Wake Forest University",
    "washington state university": "Washington State University",
    "Washington State University": "Washington State University",
    "washington university in st. louis": "Washington University in St. Louis",
    "Washington University in St. Louis": "Washington University in St. Louis",
    "wayne state university": "Wayne State University",
    "Wayne State University": "Wayne State University",
    "west virginia university": "West Virginia University",
    "West Virginia University": "West Virginia University",
    "yale university": "Yale University",
    "Yale University": "Yale University"
}

# COMMAND ----------

race_mapping = {
    1:'Black/African American',
	2:'European/Caucasian-American',
	3:'Latino/Hispanic American',
	4:'Asian/Pacific Islander/Asian-American',
	5:'Native American',
	6:'Other',
}

goal_mapping = {
    1: 'seemed like a fun night out',
	2: 'to meet new people',
	3: 'to get a date',
	4: 'looking for a serious relationship',
	5: 'to say I did it',
	6: 'other',
 }

 date_mapping = {
    1: 'Several times a week',
	2: 'Twice a week',
	3: 'Once a week',
	4:'Twice a month',
	5:'Once a month',
	6:'Several times a year',
	7:'Almost never',
 }

 go_out_mapping = {
    1:'Several times a week',
	2:'Twice a week',
	3:'Once a week',
	4:'Twice a month',
	5:'Once a month',
	6:'Several times a year',
	7:'Almost never',
 }

 length_mapping = {
     1:'Too Little',
     2:'Too Much',
     3:'Just Right', 
 }

 numdate_mapping = {
    1: 'Too Few',
	2: 'Too Many',
	3: 'Just Right',
 }
